name: charlesfraser
favicon: null
layout_spectrum: 0.6134327840991318
typography_spectrum: 0.08032381697557867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.379213530337438
  lightness: 0.204116468783468
  saturation: 0.05549662932753563
  rhythmicContrast: 0.6529296345543116
purpose: []
