name: charlesfraser
favicon: null
layout_spectrum: 0.75282
typography_spectrum: 0.49361
title: "Charles Fraser's blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff9'
    - '#020202'
    - '#35342f'
    - '#d2c6c8'
    - '#73861b'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.6529296345543116
purpose: []
